### ISSUE TITLE
Buttons do not show on Beatport

### ISSUE THREAD

**Issue by m0nkey-br4in** [murdos/musicbrainz-userscripts#154]
Import script version 2017.06.13.0 in Tampermonkey v4.3.6
Chrome on Windows version 61.0.3163.79 (Official Build) beta (64-bit)

Beatport release page lacks "import to MusicBrainz" buttons (and I don't remember what they were supposed to look like)
The page looks like this:
![screenshot 2017-09-08 17 50 09](https://user-images.githubusercontent.com/8735883/30218660-47e295be-94c2-11e7-89ed-3ff43c03bb2a.png)

Tampermonkey popup shows that the script is enabled
There is no error in the JS console that looks like `"ERROR: Execution of script 'Import Beatport releases to MusicBrainz' failed! "`
There is, however, this error:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (eval at E_c (:3:221), <anonymous>:6:2728)
    at retrieveReleaseInfo (eval at E_c (:3:221), <anonymous>:620:5)
    at HTMLDocument.eval (eval at E_c (:3:221), <anonymous>:576:17)
    at j (eval at E_c (:3:221), <anonymous>:6:26925)
    at Object.fireWith [as resolveWith] (eval at E_c (:3:221), <anonymous>:6:27738)
    at Function.ready (eval at E_c (:3:221), <anonymous>:6:29532)
    at I (eval at E_c (:3:221), <anonymous>:6:29723)
    at <anonymous>:2:398
    at b (<anonymous>:2:243)
    at t (eval at exec_fn (:1:108), <anonymous>:47:115)
```
Clicking on a link on the right that leads to its source reveals an error somewhere inside the included jQuery lib in this piece of code:
```javascript
n.extend({
    ... snip ...
    each: function(a, b, c) {
                            var d, e = 0, f = a.length, g = s(a);
                            if (c) {
                                if (g) {
                                    for (; f > e; e++)
                                        if (d = b.apply(a[e], c),
                                        d === !1)
                                            break
                                } else
                                    for (e in a)
                                        if (d = b.apply(a[e], c),
                                        d === !1)
                                            break
                            } else if (g) {
                                for (; f > e; e++)
                                    if (d = b.call(a[e], e, a[e]),
                                    d === !1)
                                        break
                            } else
                                for (e in a)
                                    if (d = b.call(a[e], e, a[e]),
                                    d === !1)
                                        break;
                            return a
                        },
    ... snip ...
```
The culprit is `a.length`

I have no real experience writing and debugging JavaScript, so the above is practically the best I can

**Comment by Ruj89** [comment]
Fixed and pulled https://github.com/murdos/musicbrainz-userscripts/pull/155

**Comment by m0nkey-br4in** [comment]
@Ruj89 I'm afraid this does not fix the issue for me
I've reinstalled the script from your pull request and still no buttons

**Comment by Ruj89** [comment]
Have you tried to refresh the release page? It seems to prevents greasemonkey to execute JS when page is loaded dinamically. This is another issue, but using f5 you could bypass it.

**Comment by m0nkey-br4in** [comment]
I know of that issue and I made sure to reload the page after initial
loading so it does not affect us here

**Comment by roman412** [comment]
The issue is still there.

**Comment by roman412** [comment]
Further investigation showed that during beatport loading this object is being created and populated, but after loading is done `window.Playables` is being wiped out in main.js. Though I have no idea how to fix it because chrome extension can't interfere in page loading as I know. 
Two alternatives can be
* using open beatport api to get tracks
* parse html page

Want other feedback, then I can try to fix it.

**Comment by m0nkey-br4in** [comment]
@roman412 for some reason well beyond my comprehension I can see MB buttons (and they work) if I load Beatport via Browsec extension (it is a proxy of some sort), but not directly.
Can there be some race condition?

**Comment by roman412** [comment]
@m0nkey-br4in I didn't see that the solution was proposed in #155 . Solution provided by @Ruj89 is more neat and it successfully resolves the issue, but it needs an improvement, see my comment here https://github.com/murdos/musicbrainz-userscripts/pull/155/commits/38ccd5702a7c2c57cf4fcafb86e0ae0069f63019#diff-2e672a0367fd7e2ba4501298c69a2286 .
I have not tried to use VPN (already trying), but can reproduce the issue on pure Chrome with standard settings and no extensions, so I guess it should be fixed somehow.

**Comment by roman412** [comment]
@m0nkey-br4in , I tried to use Browsec and friGate proxies, but the issue is still there.
As I can understand, you can't get working buttons without proxy too? Can you please try this solution to check if this solves the issue.

Insert this into Beatport tampermonkey script to line 65.
```js
if(!unsafeWindow.Playables.hasOwnProperty("tracks")) {
    eval($("#data-objects").text());
    unsafeWindow.Playables = window.Playables;
}
```

**Comment by m0nkey-br4in** [comment]
Yes, this change fixed the buttons

**Comment by roman412** [comment]
As soon as I changed the code of extension and first reloaded the page the buttons appeared. I've not noticed any other glitches.

How that pull request can be voted up? #155

**Comment by iicurtis** [comment]
The buttons are still not showing for me, even after a refresh of the page.
