### ISSUE TITLE
[BUG] VGMDb importer keeps importing the day at the 4th

### ISSUE THREAD

**Issue by CyberSkull** [murdos/musicbrainz-userscripts#361]
The VGMDb importer keeps importing the day at the 4th. Looking back, I’ve got a whole bunch of releases I’ve added with the correct year and month, but the date is the 4th on all of them.

Using with Safari/[Tampermonkey](https://www.tampermonkey.net/).

**Comment by augustjanse** [comment]
That's odd. I'll try to take a look at it this weekend.

**Comment by augustjanse** [comment]
I looked at it this weekend! Unfortunately, I tried importing with Chrome/Tampermonkey and couldn't reproduce the issue. I don't really have access to a Mac for now to try it in Safari. Is this still a problem for you?

Can I get anyone else running Safari to try to reproduce?

**Comment by CyberSkull** [comment]
I just tested this again by importing https://vgmdb.net/album/110091 and the date I got now is:
```
date.day: 5
date.month: 4
date.year: 2021
```

The release date on the album is Apr 03, 2021.

According to https://vgmdb.info/album/110091?format=json the date is:
```
"release_date": "2021-04-03”,
```

I’ll be testing on another Mac in a bit. I’ve tried reinstalling the user script and getting the same error.

**Comment by CyberSkull** [comment]
I just tried with Chrome/Tampermonkey on the same computer and got the same date error.

**Comment by CyberSkull** [comment]
I’m getting the same bug on another Mac running Big Sur (11.x). I’m on Catalina (10.15.x).

**Comment by augustjanse** [comment]
I had the experience with those releases. I'll have a look, thanks!

**Comment by augustjanse** [comment]
I think I fixed it in #366, silly little mistake. Thanks for reporting! Feel free to [try it](https://github.com/augustjanse/musicbrainz-userscripts/raw/vgmdb-fix/vgmdb_importer.user.js) straight away if you like.

**Comment by CyberSkull** [comment]
I’m still getting an off by 1 error on your version.  I tried this and it fixed it:

```
/*
 * Returns year, month and day dict based on ISO 8601 date string.
 */
function mapDate(releaseDate) {
    const d = new Date(releaseDate);

    return { year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate() + 1 };
}
```

**Comment by CyberSkull** [comment]
After some more research I changed all the functions to UTC to adjust from timezones to the absolute value.

**Comment by augustjanse** [comment]
Nice catch, looks like it "just worked" for my locale :) I updated the PR.
